### ISSUE TITLE
Readme fixes

### ISSUE THREAD

**Issue by sagron** [puniverse/quasar-codeswap-example#1]
./gradlew :quasar-codeswap-main:jar
should be
./gradlew :quasar-codeswap-module:jar
in the README.md

also for windows instructions:
gradlew.bat :quasar-codeswap-main:build
gradlew.bat :quasar-codeswap-module:jar

**Comment by sagron** [comment]
Also Quasar is spelled as Qusar in the header

**Comment by pron** [comment]
Thank you!
